### ISSUE TITLE
[ADD] 설정창 구현

### ISSUE THREAD

**Issue by sy5072** [DeveloperAcademy-POSTECH/AppleStop-iOS#15]
## 💡 Issue

설정 창과 각 항목에 대한 기능 구현

## 📝  todo

- [x] 설정 UI 구현
- [x] 알림 설정 구현
- [x] 문의사항 메일 구현
- [x] 개인정보 처리방침, 이용약관 구현
